using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;

using System.IO;

using DotNetMatrix;

namespace AHRSInterface
{
    public partial class GyroCal : Form
    {
        delegate void displayLoggingPercentCallback(float percent_complete);
        
        public GyroCal(AHRS sensor)
        {
            int i = 0;

            InitializeComponent();

            this.sensor = sensor;

            // Add DataReceived event handler.
            sensor.DataReceivedEvent += new DataReceivedDelegate(DataReceivedEventHandler);
            sensor.confReceivedEvent += new confReceivedDelegate(confReceivedEventHandler);
            confReceivedEventHandler(i);

            data_collection_enabled = false;
            next_data_index = 0;

            loggedData = new double[SAMPLES, 3];
            threshold = 1.5 * 3.14159 / 180;

            bias = new double[3];

            calMat = new double[3, 3];
            calMat[0, 0] = 1.0;
            calMat[1, 1] = 1.0;
            calMat[2, 2] = 1.0;

            D = new GeneralMatrix(SAMPLES, 10);

            for (i = 0; i < SAMPLES; i++)
            {
                loggedData[i,0] = 0;
                loggedData[i, 1] = 0;
                loggedData[i, 2] = 0;
            }
        }

        int next_data_index;
        private AHRS sensor;

        private bool data_collection_enabled;
        
        StreamWriter logfile;
        SaveFileDialog saveFileDialog;

        const int SAMPLES = 1000;
        
        double[,] loggedData;
        double[] bias;
        double[,] calMat;
        GeneralMatrix D;
        double threshold;


        /* **********************************************************************************
        * 
        * Function: void DataReceivedEventHandler
        * Inputs: None
        * Outputs: None
        * Return Value: None
        * Dependencies: None
        * Description: 
        * 
        * Handles DataReceived events generated by the AHRS object
        * 
        * *********************************************************************************/
        void DataReceivedEventHandler(int active_channels)
        {
            float percent_complete;

            if (data_collection_enabled)
            {
                // Get the yaw, pitch, and roll angle of the most recently logged data.
                // Determine whether the angle is sufficiently different to justify logging it.
                // If so, log it.  Update the data collection progress bars as neccessary.
                //if (isUniqueVector(sensor.gyroX, sensor.gyroY, sensor.gyroZ))
                int certo = 1;
                if(certo==1)
                {
                    loggedData[next_data_index, 0] = sensor.gyroX;
                    loggedData[next_data_index, 1] = sensor.gyroY;
                    loggedData[next_data_index, 2] = sensor.gyroZ;

                    next_data_index++;

                    if (next_data_index == SAMPLES)
                    {
                        data_collection_enabled = false;

                        percent_complete = 100;
                        displayLoggingPercent(percent_complete);
                    }
                    else
                    {
                        // Update data collection bar
                        percent_complete = ((float)dataProgressBar.Maximum / (float)SAMPLES) * (float)next_data_index;

                        displayLoggingPercent(percent_complete);
                    }
                }
            }
            
        }

        private void displayLoggingPercent(float percent_complete)
        {
            if (this.gyroCalStatusText.InvokeRequired)
            {
                displayLoggingPercentCallback d = new displayLoggingPercentCallback(displayLoggingPercent);
                this.Invoke(d, new object[] { percent_complete });
            }
            else
            {
                if (percent_complete == 100)
                {
                    dataProgressBar.Value = (int)percent_complete;
                    gyroCalStatusText.Text = "Done.";
                    computegyroCalButton.Enabled = true;
                    startDataCollectionButton.Enabled = false;
                    stopDataCollectionButton.Enabled = false;
                    writeToFileButton.Enabled = true;
                }
                else
                {
                    dataProgressBar.Value = (int)percent_complete;
                    gyroCalStatusText.Text = "Collecting Data: " + percent_complete.ToString() + " %";
                }
            }
        }

        private bool isUniqueVector(double gyroX, double gyroY, double gyroZ)
        {
            int i;

            bool unique_data = true;

            for (i = 0; i < next_data_index; i++)
            {
                double dot_product = loggedData[i, 0] * gyroX + loggedData[i, 1] * gyroY + loggedData[i, 2] * gyroZ;
                double norm1 = Math.Sqrt(gyroX * gyroX + gyroY * gyroY + gyroZ * gyroZ);
                double norm2 = Math.Sqrt(loggedData[i, 0] * loggedData[i, 0] + loggedData[i, 1] * loggedData[i, 1] + loggedData[i, 2] * loggedData[i, 2]);
                double angle = Math.Acos(dot_product / (norm1 * norm2));

                if (Math.Abs(angle) < threshold)
                {
                    unique_data = false;
                }
            }

            return unique_data;
        }

        private void startDataCollectionButton_Click(object sender, EventArgs e)
        {
            data_collection_enabled = true;
            startDataCollectionButton.Enabled = false;
            stopDataCollectionButton.Enabled = true;

            gyroCalStatusText.Text = "Collecting Data";
        }

        private void stopDataCollectionButton_Click(object sender, EventArgs e)
        {
            data_collection_enabled = false;
            startDataCollectionButton.Enabled = true;
            stopDataCollectionButton.Enabled = false;

            gyroCalStatusText.Text = "Inactive";
        }

        private void gyroCalResetButton_Click(object sender, EventArgs e)
        {
            data_collection_enabled = false;
            startDataCollectionButton.Enabled = true;
            stopDataCollectionButton.Enabled = false;
            computegyroCalButton.Enabled = false;
            writeToFileButton.Enabled = false;

            calStatusText.Text = "Inactive";
            flashCommitButton.Enabled = false;
            gyroAlignmentCommitButton.Enabled = false;

            dataProgressBar.Value = 0;
            next_data_index = 0;

            gyroCalStatusText.Text = "Inactive";
        }

        private void computegyroCalButton_Click(object sender, EventArgs e)
        {
            int i,j;

            calStatusText.Text = "Computing Calibration...";
           
            bias[0] = 0;
            for (i = 0; i < SAMPLES; i++)
            {
                bias[0] += loggedData[i, 0];
            }
            bias[0] = bias[0] / SAMPLES;

            bias[1] = 0;
            for (i = 0; i < SAMPLES; i++)
            {
                bias[1] += loggedData[i, 1];
            }
            bias[1] = bias[1] / SAMPLES;

            bias[2] = 0;
            for (i = 0; i < SAMPLES; i++)
            {
                bias[2] += loggedData[i, 2];
            }
            bias[2] = bias[2] / SAMPLES;
            calMat[0, 0] = 1.0;
            calMat[0, 1] = 0.0;
            calMat[0, 2] = 0.0;
            calMat[1, 0] = 0.0;
            calMat[1, 1] = 1.0;
            calMat[1, 2] = 0.0;
            calMat[2, 0] = 0.0;
            calMat[2, 1] = 0.0;
            calMat[2, 2] = 1.0;

            gyroAlignment00.Text = calMat[0, 0].ToString();
            gyroAlignment01.Text = calMat[0, 1].ToString();
            gyroAlignment02.Text = calMat[0, 2].ToString();

            gyroAlignment10.Text = calMat[1, 0].ToString();
            gyroAlignment11.Text = calMat[1, 1].ToString();
            gyroAlignment12.Text = calMat[1, 2].ToString();

            gyroAlignment20.Text = calMat[2, 0].ToString();
            gyroAlignment21.Text = calMat[2, 1].ToString();
            gyroAlignment22.Text = calMat[2, 2].ToString();

            biasX.Text = bias[0].ToString();
            biasY.Text = bias[1].ToString();
            biasZ.Text = bias[2].ToString();

            calStatusText.Text = "Done";
            flashCommitButton.Enabled = true;
            gyroAlignmentCommitButton.Enabled = true;
        }
        private void confReceivedEventHandler( int i)
        {

            float[,] floatCalMat = new float[3, 3];
            floatCalMat = sensor.gyro_alignment;

            gyroAlignment00.Text =  floatCalMat[0, 0].ToString();
            gyroAlignment01.Text = floatCalMat[0, 1].ToString();
            gyroAlignment02.Text = floatCalMat[0, 2].ToString();

            gyroAlignment10.Text = floatCalMat[1, 0].ToString();
            gyroAlignment11.Text = floatCalMat[1, 1].ToString();
            gyroAlignment12.Text = floatCalMat[1, 2].ToString();

            gyroAlignment20.Text = floatCalMat[2, 0].ToString();
            gyroAlignment21.Text = floatCalMat[2, 1].ToString();
            gyroAlignment22.Text = floatCalMat[2, 2].ToString();

            biasX.Text = sensor.x_gyro_bias.ToString();
            biasY.Text = sensor.y_gyro_bias.ToString();
            biasZ.Text = sensor.z_gyro_bias.ToString();

        }

        private void writeToFileButton_Click(object sender, EventArgs e)
        {
            saveFileDialog = new SaveFileDialog();
            
            saveFileDialog.Filter = "LOG file|*.log|All Files|*.*";
            saveFileDialog.Title = "Set LOG file name";
            saveFileDialog.OverwritePrompt = true;

            saveFileDialog.FileOk += new CancelEventHandler(saveFileDialog_FileOK);

            saveFileDialog.ShowDialog();

        }

        private void saveFileDialog_FileOK(Object sender, EventArgs e)
        {
            int i;
            // Open the file
            if (saveFileDialog.FileName != "")
            {
                logfile = new StreamWriter(saveFileDialog.FileName);

                logfile.WriteLine("gyro_X\tgyro_Y\tgyro_Z");

                for (i = 0; i < SAMPLES; i++)
                {
                    logfile.WriteLine(loggedData[i, 0].ToString() + "\t" + loggedData[i, 1].ToString() + "\t" + loggedData[i, 2].ToString());
                }

                logfile.Close();

            }
        }

        private void gyroAlignmentCommitButton_Click(object sender, EventArgs e)
        {
            float[,] floatCalMat = new float[3, 3];
            floatCalMat[0, 0] = (float)calMat[0, 0];
            floatCalMat[0, 1] = (float)calMat[0, 1];
            floatCalMat[0, 2] = (float)calMat[0, 2];

            floatCalMat[1, 0] = (float)calMat[1, 0];
            floatCalMat[1, 1] = (float)calMat[1, 1];
            floatCalMat[1, 2] = (float)calMat[1, 2];

            floatCalMat[2, 0] = (float)calMat[2, 0];
            floatCalMat[2, 1] = (float)calMat[2, 1];
            floatCalMat[2, 2] = (float)calMat[2, 2];

            sensor.gyro_alignment = floatCalMat;
            sensor.x_gyro_bias = (float)bias[0];
            sensor.y_gyro_bias = (float)bias[1];
            sensor.z_gyro_bias = (float)bias[2];

            sensor.synch();
        }

        private void flashCommitButton_Click(object sender, EventArgs e)
        {
            sensor.WriteToFlash();
           
        }

        private void gyroCal_Load(object sender, EventArgs e)
        {

        }

        private void button1_Click(object sender, EventArgs e)
        {
            sensor.automaticgyrobiasingcorrection();
        }

    }
}
